import os
API_ID = int(os.environ.get("API_ID", None))
API_HASH = os.environ.get("API_HASH", None) 
BOT_TOKEN = os.environ.get("BOT_TOKEN", None) 
OPENAI_KEY = os.environ.get("OPENAI_KEY",None)
BOT_USERNAME = os.environ.get("BOT_USERNAME" ,None) 
SUDO=os.environ.get("SUDO","6566179661")
BOT_NAME = os.environ.get("BOT_NAME",None)
START_IMG = os.environ.get("START_IMG","https://te.legra.ph/file/9fa2101b77407dbec7d31.jpg")
STKR = os.environ.get("STKR","CAACAgUAAxkBAAJcMGW7qaGTIPfrAAG20xGQ7_JWZoHBNAACRQ0AAhmMAVVD3RNN4XiZkR4E")
BANNED_USERS=os.environ.get("BANNED_USERS",None)
UPDATE_CHNL = os.environ.get("UPDATE_CHNL",None)
OWNER_USERNAME = os.environ.get("OWNER_USERNAME",None)
SUDO=os.environ.get("SUDO","5910057231")
SUPPORT_GRP = os.environ.get("SUPPORT_GRP","")
BARD_TOKEN=os.environ.get("BARD_TOKEN","")
